---
http_interactions:
- request:
    method: get
    uri: https://api.therealreal.com/v2/products/2754027
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Language:
      - en
      Currency:
      - USD
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Server:
      - Cowboy
      Cache-Control:
      - public, max-age=60
      Content-Type:
      - application/vnd.therealreal.v2+json; charset=utf-8
      Via:
      - 1.1 varnish
      - 1.1 vegur
      Content-Length:
      - '678'
      Accept-Ranges:
      - bytes
      Date:
      - Mon, 05 Dec 2016 00:59:02 GMT
      Age:
      - '0'
      Connection:
      - keep-alive
      X-Served-By:
      - cache-sjc3632-SJC
      X-Cache:
      - MISS
      X-Cache-Hits:
      - '0'
      X-Timer:
      - S1480899542.497453,VS0,VE392
      Vary:
      - Currency,Membership,Accept-Encoding
    body:
      encoding: ASCII-8BIT
      string: '{"product":{"id":"2754027","sku":"SON23351","name":"Embroidered Crew
        Neck Sweater","disclaimers":[],"description":"Black Sonia Rykiel sweater with
        scoop neckline, embroidered mini sweater at front and tonal stitching throughout.
        ","condition":"Very Good","quantity":1,"price":{"value":"95.0","currency":"USD"},"discount":null,"msrp":null,"dimensions":{"width":null,"height":null,"depth":null},"href":"https://www.therealreal.com/products/women/clothing/knitwear/sonia-rykiel-embroidered-crew-neck-sweater","links":{"designer":"1256","artist":null,"category":"5","return_policy":"refund","attributes":[]},"images":[{"rel":"main","media":[{"size":"medium","src":"https://product-images2.therealreal.com/SON23351_1_product.jpg"},{"size":"large","src":"https://product-images2.therealreal.com/SON23351_1_enlarged.jpg"}]},{"rel":"main","media":[{"size":"medium","src":"https://product-images2.therealreal.com/SON23351_2_product.jpg"},{"size":"large","src":"https://product-images2.therealreal.com/SON23351_2_enlarged.jpg"}]},{"rel":"main","media":[{"size":"medium","src":"https://product-images2.therealreal.com/SON23351_3_product.jpg"},{"size":"large","src":"https://product-images2.therealreal.com/SON23351_3_enlarged.jpg"}]},{"rel":"main","media":[{"size":"medium","src":"https://product-images2.therealreal.com/SON23351_4_product.jpg"},{"size":"large","src":"https://product-images2.therealreal.com/SON23351_4_enlarged.jpg"}]},{"rel":"main","media":[{"size":"medium","src":"https://product-images2.therealreal.com/SON23351_5_product.jpg"},{"size":"large","src":"https://product-images2.therealreal.com/SON23351_5_enlarged.jpg"}]},{"rel":"main","media":[{"size":"medium","src":"https://product-images2.therealreal.com/SON23351_6_product.jpg"},{"size":"large","src":"https://product-images2.therealreal.com/SON23351_6_enlarged.jpg"}]}],"sizes":[{"type":"clothing","value":"L"}],"availability":{"type":"available","name":"Available"},"components":[{"links":{"attributes":["66440","64124","63659"]}}],"notes":[{"label":"Fabric","content":"100%
        Cotton"},{"label":"Condition","content":"Light wear at seams."}],"made_on":null,"promotion":{"label":"20%
        Off Code: GIFT","code":"GIFT"}}}

'
    http_version: 
  recorded_at: Mon, 05 Dec 2016 00:59:02 GMT
recorded_with: VCR 3.0.3
